Flask_v4/views/item.py
from flask import Blueprint, request, render_template
from sqlalchemy import func

from functions.calc_pages import calc_pages
from models.model import Item, Order, OrderItem


item_bp = Blueprint('item', __name__)

@item_bp.route('/item/')
def item():
    page = request.args.get('page', default=1, type=int)

    per_page = 10

    data = Item.query.all()
    headers = ['Id', 'Name', 'Type', 'Unit_Price']
    total_pages, page, page_data = calc_pages(data, per_page, page)

    return render_template('item.html', headers=headers, total_pages=total_pages, page_data=page_data, current_page=page)

@item_bp.route('/item_detail/<id>')
def item_detail(id):
    data = Item.query \
            .with_entities(
                Item.type,
                Item.unit_price
            ) \
            .filter(Item.id == id) \
            .first()
    headers = ['Type', 'Unit_Price']

    # 월간 매출액
    month_datas = Order.query \
                .join(OrderItem, Order.id == OrderItem.order_id) \
                .join(Item, OrderItem.item_id == Item.id) \
                .with_entities(
                    func.SUBSTRING(Order.ordered_at, 1, 7).label('Month'),
                    func.sum(Item.unit_price).label('TotalRevenue'),
                    func.count().label('ItemCount')
                ) \
                .filter(Item.id == id) \
                .group_by('Month') \
                .all()  
    month_headers = ['Month', 'Total Revenue', 'Item Count']
    
    labels = []
    values = []
    values2 = []
    for month_data in month_datas:
        label, value, value2 = month_data
        labels.append(label)
        values.append(value)
        values2.append(value2)

    return render_template('item_detail.html', data=data, headers=headers, month_headers=month_headers, month_datas=month_datas, rows=month_datas, labels=labels, values=values, values2=values2)

Flask_v4/views/order.py
from flask import Blueprint, request, render_template

from functions.calc_pages import calc_pages
from models.model import Order, OrderItem

order_bp = Blueprint('order', __name__)

@order_bp.route('/order/')
def order():
    page = request.args.get('page', default=1, type=int)

    per_page = 10

    datas = Order.query.all()
    headers = ['Id', 'Ordered_At', 'User_Id', 'Store_Id']

    total_pages, page, page_data = calc_pages(datas, per_page, page)

    return render_template('order.html', headers=headers, page_data=page_data, total_pages=total_pages, current_page=page)

@order_bp.route('/order_detail/<id>')
def order_detail(id):
    data = OrderItem.query \
            .join(Order, Order.id == OrderItem.order_id) \
            .with_entities(
                Order.id,
                Order.ordered_at,
                Order.user_id,
                Order.store_id
            ) \
            .filter(OrderItem.order_id == id) \
            .first()
    headers = ['Id', 'Ordered_At', 'User_Id', 'Store_Id']
    print(data)

    return render_template('order_detail.html', data=data, headers=headers)

Flask_v4/views/orderitem.py
from flask import Blueprint, request, render_template

from functions.calc_pages import calc_pages
from models.model import OrderItem, Order, Item

orderitem_bp = Blueprint('orderitem', __name__)

@orderitem_bp.route('/orderitem/')
def orderitem():
    page = request.args.get('page', default=1, type=int)

    per_page = 10

    datas = OrderItem.query.all()
    headers = ['Id', 'Order_Id', 'Item_Id']

    total_pages, page, page_data = calc_pages(datas, per_page, page)

    return render_template('orderitem.html', headers=headers, page_data=page_data, total_pages=total_pages, current_page=page)

@orderitem_bp.route('/orderitem_detail/<id>')
def orderitem_detail(id):
    datas = OrderItem.query \
            .join(Order, Order.id == OrderItem.order_id) \
            .join(Item, Item.id == OrderItem.item_id) \
            .with_entities(
                OrderItem.id,
                OrderItem.order_id,
                OrderItem.item_id,
                Item.name
            ) \
            .filter(Order.id == id) \
            .all()
    headers = ['Id', 'Order_Id', 'Item_Id', 'Name']
      
    return render_template('orderitem_detail.html', data=datas, headers=headers)

Flask_v4/views/store.py
from flask import Blueprint, request, render_template
from sqlalchemy import func, desc

from functions.calc_pages import calc_pages
from models.model import Store, Order, User, OrderItem, Item

store_bp = Blueprint('store', __name__)

@store_bp.route('/store/')
def store():
    page = request.args.get('page',default=1, type=int)

    per_page = 10

    datas = Store.query.all()
    headers = ['Id', 'Name', 'Type', 'Address']

    total_pages, page, page_data = calc_pages(datas, per_page, page)

    return render_template('store.html', headers=headers, page_data=page_data, total_pages=total_pages, current_page=page)

@store_bp.route('/store_detail/<id>')
def store_detail(id):

    data = Store.query.filter(Store.id == id).first()
    headers = ['Name', 'Type', 'Address']

    # 단골 고객
    freq_data = Store.query \
                .join(Order, Store.id == Order.store_id) \
                .join(User, Order.user_id == User.id) \
                .with_entities(
                    User.id.label('user_id'),
                    User.name.label('name'),
                    func.count().label('frequency')
                ) \
                .filter(Store.id == id) \
                .group_by('user_id') \
                .order_by(User.name) \
                .limit(8).all()      
    freq_headers = ['User_Id', 'Name', 'Count']

    # 월간 매출액 detail
    month = request.args.get('month')
    
    if month:
        # 월간 매출액(일별)
        option = 0
        month_data = Store.query \
                    .join(Order, Order.store_id == Store.id) \
                    .join(OrderItem, Order.id == OrderItem.order_id) \
                    .join(Item, OrderItem.item_id == Item.id) \
                    .with_entities(
                        func.SUBSTRING(Order.ordered_at, 1, 10).label('Month'),
                        func.sum(Item.unit_price).label('Revenue'),
                        func.count().label('Count')
                    ) \
                    .filter(Store.id == id, func.SUBSTRING(Order.ordered_at, 1, 7) == month) \
                    .group_by('Month') \
                    .order_by(desc('Month')) \
                    .all()
        month_headers = ['Month', 'Revenue', 'Count']

    else:
        # 월간 매출액
        option = 1
        month_data = Store.query \
                    .join(Order, Store.id == Order.store_id) \
                    .join(OrderItem, Order.id == OrderItem.order_id) \
                    .join(Item, OrderItem.item_id == Item.id) \
                    .with_entities(
                        func.SUBSTRING(Order.ordered_at, 1, 7).label('Month'),
                        func.sum(Item.unit_price).label('Revenue'),
                        func.count().label('Count')
                    ) \
                    .filter(Store.id == id) \
                    .group_by('Month') \
                    .all()
        month_headers = ['Month', 'Revenue', 'Count']

    return render_template('store_detail.html', data=data, headers=headers, month_headers=month_headers, month_data=month_data, freq_headers=freq_headers, freq_data=freq_data, option=option)

Flask_v4/views/user.py
from flask import Blueprint, request, render_template
from sqlalchemy import case, func, desc

from functions.calc_pages import calc_pages
from models.model import User, Order, Store, OrderItem, Item


user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def index():
    page = request.args.get('page', default=1, type=int)
    search_name = request.args.get('name', default ="", type=str).strip() 
    search_gender = request.args.get('gender', default="", type=str)

    per_page = 10

    # 검색 결과에 따른 데이터 보여주기    
    users_seach = User.query \
                    .filter(
                    User.name.like('%'+search_name+'%'), 
                    User.gender.like(search_gender+'%') 
                    ) \
                    .all()
        
    # 페이지 계산
    total_pages, page, page_data = calc_pages(users_seach, per_page, page)

    headers = ['Id', 'Name', 'Gender', 'Age', 'Birthdate', 'Address']

    # 연령대별 고객 수 그래프
    bar_datas = User.query \
                .with_entities(
                    case(
                        (User.age < 20, '10대'),
                        (User.age.between(20, 29), '20대'),
                        (User.age.between(30, 39), '30대'),
                        (User.age.between(40, 49), '40대'),
                        (User.age.between(50, 59), '50대'),
                        (User.age >= 60, '60대 이상'),
                        else_='기타'
                    ).label('age_group'),
                    func.count().label('age_count')
                ) \
                .group_by('age_group').all()

    labels = []
    values = []
    for bar_data in bar_datas:
        label, value = bar_data
        labels.append(label)
        values.append(value)

    count_data = User.query.count()

    return render_template('users.html', headers=headers, page_data=page_data, total_pages=total_pages, search_name=search_name, search_gender=search_gender, current_page=page, rows=bar_datas, labels=labels, values=values, count_data=count_data)

@user_bp.route('/user_detail/<id>')
def user_detail(id):

    data = User.query.filter(User.id == id).first()
    headers = ['Name', 'Gender', 'Age',	'Birthdate', 'Address']

    # 주문 정보
    order_data = User.query \
                .join(Order, User.id == Order.user_id) \
                .join(Store, Store.id == Order.store_id) \
                .with_entities(
                    Order.id.label('OrderId'),
                    Order.ordered_at.label('PurchasedDate'),
                    Order.store_id.label('PurchasedLocation')
                ) \
                .filter(User.id == id) \
                .order_by(desc('PurchasedDate')) \
                .all()
    order_headers = ['Order_Id','Purchased Date', 'Purchased Location']

    # 자주 방문한 매장 Top 5
    visit_stores = User.query \
                    .join(Order, User.id == Order.user_id) \
                    .join(Store, Store.id == Order.store_id) \
                    .with_entities(
                        Store.name.label('name'),
                        func.count().label('count')
                    ) \
                    .filter(User.id == id) \
                    .group_by(Store.name) \
                    .order_by('count') \
                    .limit(5).all()

    # 자주 주문한 상품명 Top 5
    order_items = User.query \
                    .join(Order, Order.user_id == User.id) \
                    .join(Store, Store.id == Order.store_id) \
                    .join(OrderItem, Order.id == OrderItem.order_id) \
                    .join(Item, OrderItem.item_id == Item.id) \
                    .with_entities(
                        Item.name.label('name'),
                        func.count().label('count')
                    ) \
                    .filter(User.id == id) \
                    .group_by(Item.name) \
                    .order_by('count') \
                    .limit(5).all()
 
    return render_template('user_detail.html', data=data, headers=headers, order_headers=order_headers, order_data=order_data, visit_stores=visit_stores, order_items=order_items)

Flask_v4/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
    <script defer src="{{url_for('static', filename='script.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% endblock %}   
</head>
<body>
    <div class="wrapper">
    <!-- 네비게이션 -->
    {% block nav %}
    <div>
        <nav>
            <div class="maintain"></div>
            <ul class="main-nav">
                <li><a href="{{ url_for('user.index') }}">user</a></li>
                <li><a href="{{ url_for('store.store') }}">store</a></li>
                <li><a href="{{ url_for('order.order') }}">order</a></li>
                <li><a href="{{ url_for('orderitem.orderitem') }}">orderitem</a></li>
                <li><a href="{{ url_for('item.item') }}">item</a></li>
            </ul>
        </nav>
    </div>
    {% endblock %}

    <!-- 검색 바 -->
    {% block search %}
    <div class="other_search"></div>
    {% endblock %}

    {% block content %}
    <!-- 메인 콘텐츠 -->
    {% endblock %}
    
    <!-- 페이지 네이션 -->
    {% block pagination %}
    <div class="page_num">
        {% if total_pages < 6 %}
            {% for num in range(1, total_pages + 1) %}
                <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{num}}" class="button">{{ num }}</a>
            {% endfor %}
        {% elif current_page < 6 %}
            {% for num in range(1, 6) %} 
                <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{num}}" class="button">{{ num }}</a>
            {% endfor %}
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page=6" class="button">다음</a>
        {% elif current_page > total_pages-6 %}
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page=1" class="button">처음</a>
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{ current_page-5 }}" class="button">이전</a>
            {% for num in range(total_pages-5, total_pages+1) %}
                <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{num}}" class="button">{{ num }}</a>
            {% endfor %}
        {% else %}
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page=1" class="button">처음</a>
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{ current_page-5 }}" class="button">이전</a>
            {% for num in range(current_page, current_page+5) %}
                <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{num}}" class="button">{{ num }}</a>
            {% endfor %}
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{ current_page+5 }}" class="button">이후</a>
            <a href="?name={{ search_name }}&gender={{ search_gender }}&page={{ total_pages }}"class="button">끝</a>
        {% endif %}
    </div>
    {% endblock %}

    {% block goback %}
    <!-- 뒤로가기 버튼 -->
    {% endblock %}
</div>
{% block graph %}
<!-- 그래프 -->
{% endblock %}
</body>
</html>

Flask_v4/templates/base_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script defer src="{{url_for('static', filename='script.js')}}"></script>
    {% endblock %}
</head>
<body>
    <div class="wrapper">
    <!-- 네비게이션 -->
    {% block nav %}
    <div>
        <nav>
            <ul class="main-nav">
                <li><a href="{{ url_for('user.index') }}">user</a></li>
                <li><a href="{{ url_for('store.store') }}">store</a></li>
                <li><a href="{{ url_for('order.order') }}">order</a></li>
                <li><a href="{{ url_for('orderitem.orderitem') }}">orderitem</a></li>
                <li><a href="{{ url_for('item.item') }}">item</a></li>
            </ul>
        </nav>
    </div>
    {% endblock %}

    <!-- 검색 바 -->
    {% block search %}
    <div class="search">
        <div class="search_name">
        <form action="/" method="get">
            <label for="Name">Name: </label>
            <input type="text" name="name" value="{{ search_name }}" >
        </div>
        <div class="search_gender">
            <label for="gender">gender: </label>
            <select name="gender" id="">
                <option value=""></option>
                <option value="Male" {% if search_gender == "Male" %}selected{% endif %} >Male</option>
                <option value="Female" {% if search_gender == "Female" %}selected{% endif %}>Female</option>
            </select>
            <button type="submit">검색</button>
        </div>    
        </form>
    </div>
    {% endblock %}

    {% block content %}
    <!-- 데이블 테이터 -->
    {% endblock %}
    
    <!-- 뒤로가기 버튼 -->
    {% block goback %}
    <div class="goback">
        <p><a href="{{ url_for('user.index') }}" class="button">Go Home</a></p>
        <p><a href="{{ request.referrer }}" class="button">Back</a></p>
    </div>
    {% endblock %}
</div>
{% block chart %}
<!-- 차트 -->
{% endblock %}
</body>
</html>

Flask_v4/templates/item.html
{% extends "base.html" %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
            {% for data in page_data %}
            <tr onclick="window.location='/item_detail/{{ data['id']}}'">
                    <td><a href="/item_detail/{{ data.id }}">{{ data.id }}</a></td>
                    <td>{{ data.name }}</td>
                    <td>{{ data.type }}</td>
                    <td>{{ data.unit_price }}</td>
                </tr>
            {% endfor %} 
    </table>
</div>
{% endblock %}

Flask_v4/templates/item_detail.html
{% extends "base_detail.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
    <div>
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
   
        <tr>
            <td>{{ data.type }}</td>
            <td>{{ data.unit_price }}</td>
        </tr>   
    </table>

    <div class="detail_name">월간 매출액</div>
    <div class="detail_container">
    <table>
        <tr>
            {% for header in month_headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>

        {% for month_data in month_datas %}
        <tr>
            <td>{{ month_data.Month }}</td>
            <td>{{ month_data.TotalRevenue }}</td>
            <td>{{ month_data.ItemCount }}</td>
        </tr> 
        {% endfor %}  

    </table>
    </div>
    </div>
{% endblock %}

{% block chart %}
<div class="wrapper chart">
    월별 매출액 차트
    <div>
        <canvas id="MonthlySales_Chart"></canvas>
    </div>
    <script> 
    const labels = {{ labels | tojson }}; 
    const data = {{ values | tojson }};
    const data2 = {{ values2 | tojson }};        
    </script>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script defer src="{{url_for('static', filename='script.js')}}"></script>
{% endblock %}

Flask_v4/templates/order.html
{% extends "base.html" %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
        {% for data in page_data %}
        <tr onclick="window.location='/orderitem_detail/{{ data.id }}'">
                <td><a href="/orderitem_detail/{{ data.id }}">{{ data.id }}</a></td>
                <td>{{ data.ordered_at }}</td>
                <td>{{ data.user_id }}</td>
                <td>{{ data.store_id }}</td>
            </tr>
        {% endfor %} 
    </table>
</div>
{% endblock %}

Flask_v4/templates/order_detail.html
{% extends "base_detail.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
   
        <tr>
            <td>{{ data.id }}</td>
            <td>{{ data.ordered_at }}</td>
            <td><a href="/user_detail/{{ data.user_id }}">{{ data.user_id }}</a></td>
            <td><a href="/store_detail/{{ data.store_id }}">{{ data.store_id }}</a></td>
        </tr>   
    </table>
    </div>

{% endblock %}

Flask_v4/templates/orderitem.html
{% extends "base.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
        {% for data in page_data %}
        <tr>
            <td>{{ data.id }}</td>
            <td><a href="/order_detail/{{ data.order_id }}">{{ data.order_id }}</a></td>
            <td><a href="/item_detail/{{ data.item_id }}">{{ data.item_id }}</a></td>
        </tr>
        {% endfor %} 
    </table>
</div>
{% endblock %}
   

Flask_v4/templates/orderitem_detail.html
{% extends "base_detail.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
        
        {% for d in data %}
        <tr>
            <td>{{ d.id }}</td>
            <td><a href="/order_detail/{{ d.order_id }}">{{ d.order_id }}</a></td>
            <td><a href="/item_detail/{{ d.item_id }}">{{ d.item_id }}</a></td>
            <td>{{ d.name }}</td>
        </tr> 
        {% endfor %}  
    </table>
    </div>

{% endblock %}

Flask_v4/templates/store.html
{% extends "base.html" %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>   
        {% for data in page_data %}
        <tr onclick="window.location='/store_detail/{{ data.id }}'">
            <td><a href="/store_detail/{{ data.id }}">{{ data.id }}</a></td>
            <td>{{ data.name }}</td>
            <td>{{ data.type }}</td>
            <td>{{ data.address }}</td>
        </tr>
        {% endfor %} 
    </table>
</div>
{% endblock %}

Flask_v4/templates/store_detail.html
{% extends "base_detail.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
    <div>
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
   
        <tr>
            <td>{{ data.name }}</td>
            <td>{{ data.type }}</td>
            <td>{{ data.address }}</td>
        </tr>   
    </table>

    
    <div class="detail_container">
        {% if option == 0 %}
            <div class="detail_name">월간 매출액(일별)</div>
            <table>
                <tr>
                    {% for header in month_headers %}
                        <th>{{ header }}</th>
                    {% endfor %}
                </tr>

                {% for d in month_data %}
                <tr>
                    <td>{{ d.Month }}</td>
                    <td>{{ d.Revenue }}</td>
                    <td>{{ d.Count }}</td>
                </tr> 
                {% endfor %}  
            </table>
        {% else %}
            <div class="detail_name">월간 매출액</div>
            <table>
                <tr>
                    {% for header in month_headers %}
                        <th>{{ header }}</th>
                    {% endfor %}
                </tr>

                {% for d in month_data %}
                <tr onclick="window.location='?month={{ d.Month }}'" >
                    <td><a href="?month={{ d.Month }}">{{ d.Month }}</a></td>
                    <td>{{ d.Revenue }}</td>
                    <td>{{ d.Count }}</td>
                </tr>
                {% endfor %} 
            </table>        
        {% endif %}

        <div class="detail_name">단골 고객</div>
        <div >
            <table>
                <tr>
                    {% for header in freq_headers %}
                        <th>{{ header }}</th>
                    {% endfor %}
                </tr>
        
                {% for data in freq_data %}
                <tr>
                    <td><a href="/user_detail/{{ data.user_id }}">{{ data.user_id }}</a></td>
                    <td>{{ data.name }}</td>
                    <td>{{ data.frequency }}</td>
                </tr> 
                {% endfor %}  
            </table>
        </div>
    </div>
{% endblock %}

Flask_v4/templates/user_detail.html
{% extends "base_detail.html" %}

{% block search %}
<div class="other_search"></div>
{% endblock %}

{% block content %}
    <div>
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
   
        <tr>
            <td>{{ data.name }}</td>
            <td>{{ data.gender }}</td>
            <td>{{ data.age }}</td>
            <td>{{ data.birthdate }}</td>
            <td>{{ data.address }}</td>
        </tr>   
    </table>

    <div class="detail_name">주문 정보</div>
    <div class="detail_container">
    <table>
        <tr>
            {% for header in order_headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>

        {% for data in order_data %}
        <tr>
            <td><a href="/orderitem_detail/{{ data.OrderId }}">{{ data.OrderId }}</a></td>
            <td>{{ data.PurchasedDate }}</td>
            <td><a href="/store_detail/{{ data.PurchasedLocation }}">{{ data.PurchasedLocation }}</a></td>
        </tr> 
        {% endfor %}  

    </table>
        <div class="detail_name">자주 방문한 매장 Top 5</div>
        <ul>
            {% for visit_store in visit_stores %}
            <li>{{visit_store.name}} ({{visit_store.count}}번 방문)</li>
            {% endfor %}
        </ul>

        <div class="detail_name">자주 주문한 상품명 Top 5</div>
        <ul>
            {% for order_item in order_items %}
            <li>{{order_item.name}} ({{order_item.count}}번 주문)</li>
            {% endfor %}
        </ul>
    </div>
    </div>
{% endblock %}

Flask_v4/templates/users.html
{% extends "base.html" %}

{% block search %}
    <div class="search">
        <div class="search_name">
        <form action="/" method="get">
            <label for="Name">Name: </label>
            <input type="text" name="name" value="{{ search_name }}" >
        </div>
        <div class="search_gender">
            <label for="gender">gender: </label>
            <select name="gender" id="">
                <option value=""></option>
                <option value="Male" {% if search_gender == "Male" %}selected{% endif %} >Male</option>
                <option value="Female" {% if search_gender == "Female" %}selected{% endif %}>Female</option>
            </select>
            <button type="submit">검색</button>
        </div>    
        </form>
    </div>
{% endblock %}

{% block content %}
<div class="main_container">
    <table border="1">
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
        {% for data in page_data %}
        <tr onclick="window.location='/user_detail/{{ data.id }}'">
            <td><a href="/user_detail/{{ data.id }}">{{ data.id }}</a></td>
            <td>{{ data.name }}</td>
            <td>{{ data.gender }}</td>
            <td>{{ data.age }}</td>
            <td>{{ data.birthdate }}</td>
            <td>{{ data.address }}</td>
        </tr>
        {% endfor %} 
    </table>
    </div>
{% endblock %}

{% block graph %}
<div class="wrapper chart">
    
    <h3>연령대별 고객 수(총 {{ count_data }}명)</h3>
    <div>
        <canvas id="AgeGroup_Chart"></canvas>
    </div>
    <script> 
    const labels = {{ labels | tojson }}; 
    const data = {{ values | tojson }};        
    </script>
</div>
<div class="wrapper map">

</div>
{% endblock %}